diary/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.diary_page, name='diary_page'),
    path('diary/<int:pk>/', views.diary_detail, name='diary_detail'),
    path('diary/new/', views.diary_new, name='diary_new'),
    path('diary/<int:pk>/edit/', views.diary_edit, name='diary_edit'),
    path('diary/<int:pk>/remove/', views.diary_remove, name='diary_remove'),
    path('diary/<int:pk>/restore/', views.restore, name='restore'),
    path('diary/comment_remove/<int:pk>/', views.comment_remove, name='comment_remove'),
    path('diary/<int:pk>/liked_it/', views.liked_it, name='liked_it'),
    path('diary/<int:pk>/disliked_it/', views.disliked_it, name='disliked_it'),
    path('diary/image/<int:pk>/', views.image_view, name='image_view'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('', include('users.urls')),
    path('', include('places.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diary/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone

from places.models import Place


class Diary(models.Model):
    WEATHER_CHOICES = [
        ('sun', 'ясно'),
        ('cloud', 'облачно'),
        ('thundercloud', 'пасмурно'),
        ('rain', 'небольшой дождь'),
        ('rainstorm', 'сильный дождь'),
    ]
    FISHING_TIME_CHOICES = [
        ('morning', 'утро'),
        ('afternoon', 'день'),
        ('evening', 'вечер'),
        ('night', 'ночь'),
    ]

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True)
    place = models.ForeignKey(Place, on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length=50)
    published_date = models.DateTimeField(blank=True, null=True)
    catch_date = models.DateField(blank=True, null=True)
    description = models.TextField()
    feeding_type = models.CharField(max_length=30, blank=True, null=True)
    catch_type = models.CharField(max_length=50, blank=True, null=True)
    tackle_type = models.CharField(max_length=50, blank=True, null=True)
    fishing_time = models.CharField(max_length=12, choices=FISHING_TIME_CHOICES, default='morning')
    weather = models.CharField(max_length=12, choices=WEATHER_CHOICES, default='sun')
    deleted = models.BooleanField(blank=True, default=False)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def __str__(self):
        return self.name

    def comments_amount(self):
        return len(Comment.objects.filter(diary_id=self))

    def likes_amount(self):
        return len(Mark.objects.filter(diary_id=self, mark="like"))

    def dislikes_amount(self):
        return len(Mark.objects.filter(diary_id=self, mark="dislike"))


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    diary_id = models.ForeignKey(Diary, on_delete=models.CASCADE)
    description = models.TextField()
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()


class Mark(models.Model):
    MARK_TYPE_CHOICES = [
        ('like', 'нравится'),
        ('dislike', 'не нравится'),
        ('neutral', 'нейтральная'),
    ]

    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    diary_id = models.ForeignKey(Diary, on_delete=models.CASCADE)
    mark = models.CharField(max_length=12, choices=MARK_TYPE_CHOICES, default='neutral')

    def __str__(self):
        return self.mark


class Image(models.Model):
    diary_id = models.ForeignKey(Diary, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="post_images/", blank=True)

places/models.py
import math

from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.utils import timezone


def rd(x, y=0):
    m = int('1' + '0' * y)  # multiplier - how many positions to the right
    q = x * m  # shift to the right by multiplier
    c = int(q)  # new number
    i = int((q - c) * 10)  # indicator number on the right
    if i >= 5:
        c += 1
    return c / m


class Place(models.Model):
    VISIBILITY_CHOICES = [
        ('me', 'Только мне'),
        ('all', 'Всем'),
    ]

    name = models.CharField(max_length=30)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    visibility = models.CharField(max_length=3, choices=VISIBILITY_CHOICES, default='me')
    latitude = models.FloatField()
    longitude = models.FloatField()
    description = models.TextField()
    deleted = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return self.name

    def average_rating(self):
        if Rating.objects.filter(place_id=self):
            return round(Rating.objects.filter(place_id=self).aggregate(Sum('rating')).get('rating__sum', 0) / (len(Rating.objects.filter(place_id=self))), 1)
        else:
            return 0

    def rounded_average_rating(self):
        if Rating.objects.filter(place_id=self):
            avg_rate = Rating.objects.filter(place_id=self).aggregate(Sum('rating')).get('rating__sum', 0) / (len(Rating.objects.filter(place_id=self)))
            return rd(avg_rate, 0)
        else:
            return 0


class Rating(models.Model):
    place_id = models.ForeignKey(Place, on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField()
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

diary/forms.py
from django import forms
from .models import Diary, Comment, Image


class DiaryForm(forms.ModelForm):

    class Meta:
        model = Diary
        fields = (
            'name',
            'catch_date',
            'fishing_time',
            'weather',
            'place',
            'description',
            'feeding_type',
            'tackle_type',
            'catch_type',
        )
        labels = {
            'name': 'Название:',
            'catch_date': 'Дата рыбалки:',
            'fishing_time': 'Время суток:',
            'weather': 'Погода:',
            'place': 'Место:',
            'description': 'Описание:',
            'feeding_type': 'Тип прикорма:',
            'tackle_type': 'Тип снасти:',
            'catch_type': 'Тип улова:',
        }


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = {'description'}
        labels = {'description': 'Текст комментария:'}


class ImageForm(forms.ModelForm):

    class Meta:
        model = Image
        fields = {'image'}
        labels = {'image': 'Изображение:'}

diary/views.py
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.http import HttpResponseForbidden
from django.shortcuts import redirect
from django.utils import timezone
from django.forms import modelformset_factory

from places.models import Place
from .models import Diary, Comment, Mark, Image
from django.shortcuts import render, get_object_or_404
from .forms import DiaryForm, CommentForm, ImageForm


def diary_page(request):
    diary_list = Diary.objects.filter(deleted=False).filter(published_date__lte=timezone.now()).order_by('-published_date')
    paginator = Paginator(diary_list, 8)
    page = request.GET.get('page')
    try:
        diaries = paginator.page(page)
    except PageNotAnInteger:
        diaries = paginator.page(1)
    except EmptyPage:
        diaries = paginator.page(paginator.num_pages)
    return render(request, 'diary/diary_page.html', {'diaries': diaries})


def diary_detail(request, pk):
    diary = get_object_or_404(Diary, pk=pk)
    image_list = Image.objects.filter(diary_id=diary)
    comment_list = Comment.objects.filter(diary_id=diary).order_by('-published_date')

    if request.user.is_authenticated:
        try:
            user_mark = Mark.objects.get(user_id=request.user, diary_id_id=diary.pk)
        except ObjectDoesNotExist:
            user_mark = None
    else:
        user_mark = None

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.diary_id = diary
            comment.author = request.user
            comment.published_date = timezone.now()
            comment.save()
            return redirect('diary_detail', pk=diary.pk)
    else:
        form = CommentForm()

    paginator = Paginator(comment_list, 4)
    page = request.GET.get('page')
    try:
        comments = paginator.page(page)
    except PageNotAnInteger:
        comments = paginator.page(1)
    except EmptyPage:
        comments = paginator.page(paginator.num_pages)

    return render(request, 'diary/diary_detail.html', {'diary': diary, 'comments': comments,
                                                       'form': form, 'user_mark': user_mark,
                                                       'image_list': image_list})


def diary_new(request):
    header = "Новая запись"

    if request.user.is_authenticated:
        # place_choices = Place.objects.filter(visibility="me", deleted=False, author=request.user)
        # free_place_choices = Place.objects.filter(visibility="all", deleted=False)

        ImageFormSet = modelformset_factory(Image, form=ImageForm, extra=3)

        if request.method == "POST":
            diary_form = DiaryForm(request.POST)
            formset = ImageFormSet(request.POST, request.FILES, queryset=Image.objects.none())
            if diary_form.is_valid() and formset.is_valid():
                diary = diary_form.save(commit=False)
                diary.published_date = timezone.now()
                diary.author = request.user
                diary.save()
                for form in formset:
                    if 'image' in form.cleaned_data and form.cleaned_data['image']:
                        image = form.save(commit=False)
                        image.diary_id = diary
                        image.save()
                    elif 'image' in form.cleaned_data and not form.cleaned_data['image']:
                        form.cleaned_data['id'].delete()

                return redirect('diary_detail', pk=diary.pk)
        else:
            diary_form = DiaryForm()
            formset = ImageFormSet(queryset=Image.objects.none())
    else:
        return HttpResponseForbidden()

    return render(request, 'diary/diary_edit.html', {'diary_form': diary_form,
                                                     'formset': formset,
                                                     'header': header})


def diary_edit(request, pk):
    header = "Редактировать запись"
    diary = get_object_or_404(Diary, pk=pk)
    try:
        images = Image.objects.filter(diary_id=diary)
    except ObjectDoesNotExist:
        images = Image.objects.none()

    if diary.author != request.user:
        return HttpResponseForbidden()

    ImageFormSet = modelformset_factory(Image, form=ImageForm, extra=3-len(images))
    if request.method == "POST":
        diary_form = DiaryForm(request.POST, instance=diary, prefix="diary_form")
        formset = ImageFormSet(request.POST, request.FILES, queryset=images)
        if diary_form.is_valid() and formset.is_valid():
            diary = diary_form.save(commit=False)
            diary.published_date = timezone.now()
            diary.save()
            for form in formset:
                if 'image' in form.cleaned_data and form.cleaned_data['image']:
                    image = form.save(commit=False)
                    image.diary_id = diary
                    image.save()
                elif 'image' in form.cleaned_data and not form.cleaned_data['image']:
                    form.cleaned_data['id'].delete()

            return redirect('diary_detail', pk=diary.pk)
    else:
        diary_form = DiaryForm(instance=diary, prefix="diary_form")
        formset = ImageFormSet(queryset=images)

    return render(request, 'diary/diary_edit.html', {'diary_form': diary_form,
                                                     'formset': formset,
                                                     'header': header})


def diary_remove(request, pk):
    diary = get_object_or_404(Diary, pk=pk)
    if diary.author == request.user or request.user.is_staff:
        diary.deleted = True
        diary.save()
    return redirect('diary_detail', pk=diary.pk)


def restore(request, pk):
    diary = get_object_or_404(Diary, pk=pk)
    if diary.author == request.user or request.user.is_staff:
        diary.deleted = False
        diary.save()
    return redirect('diary_detail', pk=diary.pk)


def comment_remove(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    diary = get_object_or_404(Diary, pk=comment.diary_id.pk)
    if comment.author == request.user or request.user.is_staff:
        comment.delete()
    return redirect('diary_detail', pk=diary.pk)


def liked_it(request, pk):
    diary = get_object_or_404(Diary, pk=pk)
    like = Mark.objects.filter(user_id=request.user, diary_id_id=diary.pk, mark="like")

    if request.user.is_authenticated:
        if like:
            like.delete()
        else:
            like, created = Mark.objects.get_or_create(user_id=request.user, diary_id_id=diary.pk)
            like.mark = "like"
            like.save()
    else:
        return HttpResponseForbidden()
    return redirect('diary_detail', pk=diary.pk)


def disliked_it(request, pk):
    diary = get_object_or_404(Diary, pk=pk)
    dislike = Mark.objects.filter(user_id=request.user, diary_id_id=diary.pk, mark="dislike")

    if request.user.is_authenticated:
        if dislike:
            dislike.delete()
        else:
            dislike, created = Mark.objects.get_or_create(user_id=request.user, diary_id_id=diary.pk)
            dislike.mark = "dislike"
            dislike.save()
    else:
        return HttpResponseForbidden()
    return redirect('diary_detail', pk=diary.pk)


def image_view(request, pk):
    image = get_object_or_404(Image, pk=pk)
    return render(request, 'diary/image.html', {'image': image})

diary/templates/diary/base.html
{% load static %}
<html>
    <head>
        <title>Fisherman's Diary</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,cyrillic" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="{% static 'css/diary.css' %}">
    </head>
    <body>
        <div class="page-header">
            {% if user.is_authenticated %}
                <a href="{% url 'diary_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            {% endif %}
            <h1><a href="/">Дневник рыбака</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
            </div>
        </div>
</body>
</html>

diary/templates/diary/diary_detail.html
{% extends 'base_with_map.html' %}
{% load static %}
{% load l10n %}

{% block content %}
    <div class="post">
        {% if diary.published_date %}
            <div class="date">
                <p>Автор: <a href="{% url 'profile' pk=diary.author.pk %}"> {{ diary.author }}</a>
                    {{ diary.published_date }}</p>
            </div>
        {% endif %}
        {% if diary.deleted == False %}
            {% if user.is_authenticated and user == diary.author %}
                <a class="btn btn-default" href="{% url 'diary_edit' pk=diary.pk %}"><span class="glyphicon glyphicon-pencil"></span></a>
                <a class="btn btn-default" href="{% url 'diary_remove' pk=diary.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
            {% endif %}
            {% if user.is_staff and user != diary.author %}
                <a class="btn btn-default" href="{% url 'diary_remove' pk=diary.pk %}"><span class="glyphicon glyphicon-remove"></span></a>
            {% endif %}
        {% else %}
            <a class="btn btn-default" href="{% url 'restore' pk=diary.pk %}">Восстановить</a>
        {% endif %}
        <h1>{{ diary.name }}</h1>
        {% if diary.catch_date %}
            <p><b>Дата рыбалки:</b> {{ diary.catch_date}}</p>
        {% endif %}
        <p><b>Время суток:</b> {{ diary.get_fishing_time_display }}</p>
        <p><b>Погода:</b> {{ diary.get_weather_display }}</p>
        {% if diary.feeding_type %}
            <p><b>Тип прикорма:</b> {{ diary.feeding_type}}</p>
        {% endif %}
        {% if diary.tackle_type %}
            <p><b>Тип снасти:</b> {{ diary.tackle_type}}</p>
        {% endif %}
        {% if diary.catch_type %}
            <p><b>Улов:</b> {{ diary.catch_type}}</p>
        {% endif %}
        <p>{{ diary.description|linebreaksbr }}</p>

        {% for image in image_list %}
            <a href="{% url 'image_view' pk=image.pk %}"><img src="{{ MEDIA_URL }}{{ image.image.url }}" width="200px"></a>
        {% endfor %}

        {% if diary.place and diary.place.deleted == False %}
            {% if request.user == diary.author and diary.place.visibility == "me" or diary.place.visibility == "all" %}
                <div id="mapid" style="width: 600px; height: 400px;"></div>
                <script>

                    var mymap = L.map('mapid').setView([{{ diary.place.latitude|unlocalize }}, {{ diary.place.longitude|unlocalize }}], 11);

                    L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
                        maxZoom: 18,
                        attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                            '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                            'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                        id: 'mapbox.streets'
                    }).addTo(mymap);

                    L.marker([{{ diary.place.latitude|unlocalize }}, {{ diary.place.longitude|unlocalize }}]).addTo(mymap)
                    .bindPopup('<a href="{% url 'place_detail' pk=diary.place.pk %}">{{ diary.place.name}}</a>').openPopup();

                </script>
            {% else %}
                <p>Место рыбалки: секретное место</p>
            {% endif %}
        {% endif %}
    </div>


    <div>
        {% if user.is_authenticated %}
            <a name="likes" href="{% url 'liked_it' pk=diary.pk %}">
                {% if user_mark.mark == "dislike" or user_mark.mark == None %}
                    <i class="fa fa-thumbs-o-up fa-2x"></i></a>
                {% else %}
                    <i class="fa fa-thumbs-up fa-2x"></i></a>
                {% endif %}
            &nbsp;{{ diary.likes_amount }}&nbsp;&nbsp;&nbsp;
            <a name="dislikes" href="{% url 'disliked_it' pk=diary.pk %}">
                {% if user_mark.mark == "like" or user_mark.mark == None %}
                    <i class="fa fa-thumbs-o-down fa-flip-horizontal fa-2x"></i></a>
                {% else %}
                    <i class="fa fa-thumbs-down fa-flip-horizontal fa-2x"></i></a>
                {% endif %}
            &nbsp;{{ diary.dislikes_amount }}
        {% else %}
            <p>Авторизуйтесь для того, чтобы поставить отметку.</p>
        {% endif %}
    </div>

    <h1><a name="comments"></a>Комментарии:</h1>
    {% for comment in comments %}
        <br>
        <div>
            <a href="{% url 'profile' pk=comment.author.pk %}">{{ comment.author }}</a>
            <p>{{ comment.description }}</p>
            {% if user.is_authenticated and user == comment.author or user.is_staff %}
                {{ comment.published_date }} <a href="{% url 'comment_remove' pk=comment.pk %}">Удалить</a> <hr>
            {% endif %}
        </div>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if comments.has_previous %}
                <a href="?page={{ comments.previous_page_number }}">предыдущая</a>
            {% endif %}

            <span class="current">
                Страница {{ comments.number }} из {{ comments.paginator.num_pages }}
            </span>

            {% if comments.has_next %}
                <a href="?page={{ comments.next_page_number }}">Следующая</a>
            {% endif %}
        </span>
    </div>
    {% if user.is_authenticated %}
        {% if form %}
            <form method="POST" class="post-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="save btn btn-default">Сохранить</button>
            </form>
        {% endif %}
    {% else %}
        <p>Авторизуйтесь для того, чтобы оставить комментарий.</p>
    {% endif %}

{% endblock %}

diary/templates/diary/diary_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{header}}</h1>
    <form method="POST" class="post-form" enctype="multipart/form-data">{% csrf_token %}
<!--        {{ form.non_field_errors }}-->
<!--        <div>-->
<!--            {{ form.name.errors }}-->
<!--            <label for="id_name">Название:</label>-->
<!--            {{ form.name }}-->
<!--        </div>-->
<!--        <div>-->
<!--            <br>-->
<!--            {{ form.catch_date.errors }}-->
<!--            <label for="id_catch_date">Дата рыбалки:</label>-->
<!--            {{ form.catch_date }}-->
<!--        </div>-->
<!--        <div>-->
<!--            {{ form.fishing_time.errors }}-->
<!--            <label for="id_fishing_time">Время суток:</label>-->
<!--            {{ form.fishing_time }}-->
<!--        </div>-->
<!--        <div>-->
<!--            {{ form.weather.errors }}-->
<!--            <label for="id_weather">Погода:</label>-->
<!--            {{ form.weather }}-->
<!--        </div>-->
<!--        <div>-->
<!--            {{ form.place.errors }}-->
<!--            <label for="place_choices">Место:</label>-->
<!--            {{ form.place }}-->
<!--        </div>-->
<!--        <div>-->
<!--            {{ form.description.errors }}-->
<!--            <label for="id_description">Описание:</label>-->
<!--            {{ form.description }}-->
<!--        </div>-->
<!--        <div>-->
<!--            {{ form.feeding_type.errors }}-->
<!--            <label for="id_feeding_type">Тип прикорма:</label>-->
<!--            {{ form.feeding_type }}-->
<!--        </div>-->
<!--        <div>-->
<!--            {{ form.tackle_type.errors }}-->
<!--            <label for="id_tackle_type">Тип снасти:</label>-->
<!--            {{ form.tackle_type }}-->
<!--        </div>-->
<!--        <div>-->
<!--            {{ form.catch_type.errors }}-->
<!--            <label for="id_catch_type">Тип улова:</label>-->
<!--            {{ form.catch_type }}-->
<!--        </div>-->
        {{ diary_form.as_p }}
        {{ formset.management_form }}
        {% for form in formset %}
            {{ form }}
        {% endfor %}
        <button type="submit" class="save btn btn-default">Сохранить</button>
    </form>
{% endblock %}

diary/templates/diary/diary_page.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    {% for diary in diaries %}
        <div class="post">
            <div class="date">
                <p>Автор: <a href="{% url 'profile' pk=diary.author.pk %}"> {{ diary.author }}</a>
                    Опубликовано: {{ diary.published_date }}</p>
            </div>
            <h1><a href="{% url 'diary_detail' pk=diary.pk %}">{{ diary.name }}</a></h1>
            <p>{{ diary.description|linebreaksbr|truncatewords:80 }}</p>
            <p>
                <a href="{% url 'diary_detail' pk=diary.pk %}#comments "><i class="fa fa-comment-o fa-lg"></i></a>
                {{ diary.comments_amount }}&nbsp;&nbsp;
                <i class="fa fa-thumbs-o-up fa-lg"></i>
                {{ diary.likes_amount }}&nbsp;&nbsp;
                <i class="fa fa-thumbs-o-down fa-flip-horizontal fa-lg"></i>
                {{ diary.dislikes_amount }}
            </p>
        </div>
    {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if diaries.has_previous %}
                <a href="?page={{ diaries.previous_page_number }}"><i class="fa fa-chevron-left fa-lg"></i></a>
            {% endif %}
            <span class="current">
                Страница {{ diaries.number }} из {{ diaries.paginator.num_pages }}
            </span>
            {% if diaries.has_next %}
                <a href="?page={{ diaries.next_page_number }}"><i class="fa fa-chevron-right fa-lg"></i></a>
            {% endif %}
        </span>
    </div>

{% endblock %}

diary/templates/diary/image.html
{% extends 'base_with_map.html' %}
{% load static %}

{% block content %}
    <h1><a href="{% url 'diary_detail' pk=image.diary_id_id %}">Вернуться к посту</a></h1>
        {% if image %}
            <img src="{{ MEDIA_URL }}{{ image.image.url }}">
        {% endif %}
{% endblock %}

diary/templates/diary/place_edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{header}}</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.non_field_errors }}
        <div>
            {{ form.name.errors }}
            <label for="id_name">Название:</label>
            {{ form.name }}
        </div>
        <div>
            <br>
            {{ form.visibility.errors }}
            <label for="id_visibility">Кому видно:</label>
            {{ form.visibility }}
        </div>
        <div>
            {{ form.latitude.errors }}
            <label for="id_latitude">Широта:</label>
            {{ form.latitude }}
        </div>
        <div class="fieldWrapper">
            {{ form.longitude.errors }}
            <label for="id_lonitude">Долгота:</label>
            {{ form.longitude }}
        </div>
        <div class="fieldWrapper">
            {{ form.description.errors }}
            <label for="id_description">Описание:</label>
            {{ form.description }}
        </div>
        <br><button type="submit" class="save btn btn-default">Сохранить</button>
    </form>
{% endblock %}