diary/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.diary_page, name='diary_page'),
    path('diary/<int:pk>/', views.diary_detail, name='diary_detail'),
    path('diary/new/', views.diary_new, name='diary_new'),
    path('diary/<int:pk>/edit/', views.diary_edit, name='diary_edit'),
    path('diary/<int:pk>/remove/', views.diary_remove, name='diary_remove'),
    path('diary/<int:pk>/restore/', views.restore, name='restore'),
    path('diary/comment_remove/<int:pk>/', views.comment_remove, name='comment_remove'),
    path('diary/<int:pk>/liked_it/', views.liked_it, name='liked_it'),
    path('diary/<int:pk>/disliked_it/', views.disliked_it, name='disliked_it'),
    path('diary/image/<int:pk>/', views.image_view, name='image_view'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('', include('users.urls')),
    path('', include('places.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

places/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('places/user/<int:pk>', views.places, name='user_places'),
    path('places/detail/<int:pk>/', views.place_detail, name='place_detail'),
    path('places/new/', views.new_place, name='new_place'),
    path('places/<int:pk>/edit/', views.place_edit, name='place_edit'),
    path('places/remove/<int:pk>/', views.place_remove, name='place_remove'),
    path('places/<int:pk>/restore/', views.place_restore, name='place_restore'),
    path('places/map/', views.main_map, name='main_map'),
    path('places/detail/<int:pk>/rate/<int:value>', views.rate_place, name='rate_place'),
]

places/models.py
import math

from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.utils import timezone


def rd(x, y=0):
    m = int('1' + '0' * y)  # multiplier - how many positions to the right
    q = x * m  # shift to the right by multiplier
    c = int(q)  # new number
    i = int((q - c) * 10)  # indicator number on the right
    if i >= 5:
        c += 1
    return c / m


class Place(models.Model):
    VISIBILITY_CHOICES = [
        ('me', 'Только мне'),
        ('all', 'Всем'),
    ]

    name = models.CharField(max_length=30)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    visibility = models.CharField(max_length=3, choices=VISIBILITY_CHOICES, default='me')
    latitude = models.FloatField()
    longitude = models.FloatField()
    description = models.TextField()
    deleted = models.BooleanField(blank=True, default=False)

    def __str__(self):
        return self.name

    def average_rating(self):
        if Rating.objects.filter(place_id=self):
            return round(Rating.objects.filter(place_id=self).aggregate(Sum('rating')).get('rating__sum', 0) / (len(Rating.objects.filter(place_id=self))), 1)
        else:
            return 0

    def rounded_average_rating(self):
        if Rating.objects.filter(place_id=self):
            avg_rate = Rating.objects.filter(place_id=self).aggregate(Sum('rating')).get('rating__sum', 0) / (len(Rating.objects.filter(place_id=self)))
            return rd(avg_rate, 0)
        else:
            return 0


class Rating(models.Model):
    place_id = models.ForeignKey(Place, on_delete=models.CASCADE)
    user_id = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    rating = models.IntegerField()
    published_date = models.DateTimeField(blank=True, null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

places/forms.py
from django import forms
from .models import Place


class PlaceForm(forms.ModelForm):

    class Meta:
        model = Place
        fields = {
            'name',
            'visibility',
            'latitude',
            'longitude',
            'description',
        }

places/views.py
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseForbidden
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from itertools import chain

from diary.models import Diary
from places.forms import PlaceForm
from places.models import Place, Rating


def places(request, pk):
    profile_user = get_object_or_404(User, pk=pk)
    if request.user == profile_user:
        place_list = Place.objects.filter(author=profile_user)
        header = "Мои места:"
    else:
        place_list = Place.objects.filter(author=profile_user).filter(visibility="all", deleted=False)
        header = "Места пользователя " + profile_user.username + " :"
    return render(request, 'places.html', {'place_list': place_list, 'header': header, 'profile_user': profile_user})


def place_detail(request, pk):
    place = get_object_or_404(Place, pk=pk)
    profile_user = get_object_or_404(User, pk=place.author.pk)

    if request.user.is_authenticated:
        try:
            rating = Rating.objects.get(user_id=request.user, place_id_id=place.pk)
        except ObjectDoesNotExist:
            rating = None
    else:
        rating = None

    if request.user != profile_user and place.visibility == "me":
        return HttpResponseForbidden()

    if request.user == profile_user or request.user.is_staff:
        diary_list = Diary.objects.filter(place=place.pk).order_by('-published_date')
    else:
        diary_list = Diary.objects.filter(place=place.pk, deleted=False).order_by('-published_date')

    if request.user == profile_user:
        places_header = "Мои места"
    else:
        places_header = "Места пользователя " + profile_user.username

    return render(request, 'detail.html', {'place': place, 'diary_list': diary_list, 'profile_user': profile_user,
                                           'places_header': places_header, 'rating': rating})


def new_place(request):
    header = "Новое место"
    if request.user.is_authenticated:
        if request.method == "POST":
            form = PlaceForm(request.POST)
            if form.is_valid():
                place = form.save(commit=False)
                place.author = request.user
                place.save()
                return redirect('place_detail', pk=place.pk)
        else:
            form = PlaceForm()
    else:
        return HttpResponseForbidden()

    return render(request, 'edit.html', {'form': form, 'header': header})


def place_edit(request, pk):
    header = "Редактировать место"
    place = get_object_or_404(Place, pk=pk)
    if place.author != request.user:
        return HttpResponseForbidden()

    if request.method == "POST":
        form = PlaceForm(request.POST, instance=place)
        if form.is_valid():
            place = form.save(commit=False)
            place.save()
            return redirect('place_detail', pk=place.pk)
    else:
        form = PlaceForm(instance=place)
    return render(request, 'edit.html', {'form': form, 'header': header, 'place': place})


def place_remove(request, pk):
    place = get_object_or_404(Place, pk=pk)
    if place.author == request.user or request.user.is_staff:
        place.deleted = True
        place.save()
    return redirect('place_detail', pk=place.pk)


def place_restore(request, pk):
    place = get_object_or_404(Place, pk=pk)
    if place.author == request.user or request.user.is_staff:
        place.deleted = False
        place.save()
    return redirect('place_detail', pk=place.pk)


def main_map(request):
    if request.user.is_authenticated:
        secret_place_list = Place.objects.filter(author=request.user, visibility="me", deleted=False)
        another_place_list = Place.objects.filter(visibility="all", deleted=False)
        place_list = secret_place_list | another_place_list
        sorted_list = sorted(place_list, key=lambda a: a.average_rating(), reverse=True)
    else:
        secret_place_list = ""
        another_place_list = ""
        place_list = Place.objects.filter(visibility="all", deleted=False)
        sorted_list = sorted(place_list, key=lambda a: a.average_rating(), reverse=True)

    return render(request, 'map.html', {'secret_place_list': secret_place_list,
                                        'another_place_list': another_place_list,
                                        'sorted_list': sorted_list})


def rate_place(request, pk, value):
    place = get_object_or_404(Place, pk=pk)
    rating = Rating.objects.filter(user_id=request.user, place_id_id=place.pk)

    if request.user.is_authenticated:
        if rating:
            rating.delete()
            rating, created = Rating.objects.get_or_create(user_id=request.user, place_id_id=place.pk, rating=value)
            rating.published_date = timezone.now()
            rating.save()
        else:
            rating, created = Rating.objects.get_or_create(user_id=request.user, place_id_id=place.pk, rating=value)
            rating.published_date = timezone.now()
            rating.save()
    else:
        return HttpResponseForbidden()
    return redirect('place_detail', pk=place.pk)

places/templates/detail.html
{% extends 'base_with_map.html' %}
{% load static %}
{% load l10n %}

{% block content %}
    <script>
        function stars(star_hover){
            var starList = ["star1", "star2", "star3", "star4", "star5"];

            starList.forEach(function(item, i, arr) {
                if( i <= star_hover){
                    document.getElementById(item).classList.remove('fa-star-o');
                    document.getElementById(item).classList.remove('fa');
                    document.getElementById(item).classList.add('fa');
                    document.getElementById(item).classList.add('fa-star');
                }
                else{
                    document.getElementById(item).classList.remove('fa-star');
                    document.getElementById(item).classList.remove('fa');
                    document.getElementById(item).classList.add('fa');
                    document.getElementById(item).classList.add('fa-star-o');
                }
            });
        };
        function fill_stars(avg_rating){
            var starList = ["star1", "star2", "star3", "star4", "star5"];

            starList.forEach(function(item, i, arr) {
                if( i+1 <= Math.round(avg_rating)){
                    document.getElementById(item).classList.remove('fa-star-o');
                    document.getElementById(item).classList.add('fa-star');
                }
                else{
                    document.getElementById(item).classList.remove('fa-star');
                    document.getElementById(item).classList.add('fa-star-o');
                }
            });
        };

        function fill_stars_for_anonymous(avg_rating){
            var starList = ["rating1", "rating2", "rating3", "rating4", "rating5"];

            starList.forEach(function(item, i, arr) {
                if( i+1 <= Math.round(avg_rating)){
                    document.getElementById(item).classList.remove('fa-star-o');
                    document.getElementById(item).classList.add('fa-star');
                }
                else{
                    document.getElementById(item).classList.remove('fa-star');
                    document.getElementById(item).classList.add('fa-star-o');
                }
            });
        };
    </script>

    <div class="post">
        <div class="date">
            <p>Автор: <a href="{% url 'profile' pk=place.author.pk %}"> {{ place.author }}</a>
        </div>
        <h1><a href="{% url 'user_places' pk=profile_user.pk %}">{{ places_header }}/ </a>{{ place.name }}</h1>

        {% if place.deleted == False %}
            {% if user.is_authenticated and user == place.author %}
                <p><a href="{% url 'place_edit' pk=place.pk %}">редактировать</a>
                    <a href="{% url 'place_remove' pk=place.pk %}"> удалить</a></p>
            {% endif %}
            {% if user.is_staff and user != place.author %}
                <p><a href="{% url 'place_remove' pk=place.pk %}"> удалить</a></p>
            {% endif %}
        {% else %}
            <a href="{% url 'place_restore' pk=place.pk %}">Восстановить</a>
        {% endif %}

        <p>Координаты: {{place.latitude }}, {{ place.longitude }}</p>
        <p>{{ place.description|linebreaksbr }}</p>

        <div>
            {% if user.is_authenticated %}
                <p>
                    {% if rating %}
                        Моя оценка: {{ rating.rating }}
                    {% else %}
                        Вы ещё не оценивали это место
                    {% endif %}
                </p>
                <p>
                    Оцените место:
                    <a onmouseover="stars(0)" href="{% url 'rate_place' pk=place.pk value=1 %}"><i id="star1" class="fa fa-star-o" ></i></a>
                    <a onmouseover="stars(1)" href="{% url 'rate_place' pk=place.pk value=2 %}"><i id="star2" class="fa fa-star-o"></i></a>
                    <a onmouseover="stars(2)" href="{% url 'rate_place' pk=place.pk value=3 %}"><i id="star3" class="fa fa-star-o"></i></a>
                    <a onmouseover="stars(3)" href="{% url 'rate_place' pk=place.pk value=4 %}"><i id="star4" class="fa fa-star-o"></i></a>
                    <a onmouseover="stars(4)" href="{% url 'rate_place' pk=place.pk value=5 %}"><i id="star5" class="fa fa-star-o"></i></a>
                    {{ place.average_rating }}
                </p>
            {% else %}
                <p>
                    <i id="rating1" class="fa fa-star-o" ></i></a>
                    <i id="rating2" class="fa fa-star-o"></i></a>
                    <i id="rating3" class="fa fa-star-o"></i></a>
                    <i id="rating4" class="fa fa-star-o"></i></a>
                    <i id="rating5" class="fa fa-star-o"></i></a>
                    {{ place.average_rating }}
                </p>
                <p>Авторизуйтесь для того, чтобы поставить оценку.</p>
            {% endif %}
        </div>

        {% if diary_list %}
            <h1>Записи, связанные с этим местом:</h1>
            {% for diary in diary_list %}
                <div>
                    <a href="{% url 'diary_detail' pk=diary.pk %}">{{ diary.name }}</a><br>
                    {{ diary.published_date }}&nbsp;
                    <a href="{% url 'diary_detail' pk=diary.pk %}#comments"><i class="fa fa-comment-o"></i></a>
                    {{ diary.comments_amount }}&nbsp;
                    <i class="fa fa-thumbs-o-up"></i>
                    {{ diary.likes_amount }}&nbsp;
                    <i class="fa fa-thumbs-o-down fa-flip-horizontal"></i>
                    {{ diary.dislikes_amount }}&nbsp;
                    <b>{% if diary.deleted == True %} Удалён {% endif %}</b><br><br>
                </div>
            {% endfor %}
        {% else %}
            <h1>С этим местом пока не связана ни одна запись.</h1>
        {% endif %}
    </div>

    <div id="mapid" style="width: 600px; height: 400px;"></div>
    <script>

        var mymap = L.map('mapid').setView([{{ place.latitude|unlocalize }}, {{ place.longitude|unlocalize }}], 11);

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
            maxZoom: 18,
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            id: 'mapbox.streets'
        }).addTo(mymap);

        L.marker([{{ place.latitude|unlocalize }}, {{ place.longitude|unlocalize }}]).addTo(mymap)
        .bindPopup("{{ place.name }}").openPopup();


    </script>
    <script type="text/javascript">
        {% if user.is_authenticated %}
            fill_stars({{ place.average_rating|unlocalize }});
        {% else %}
            fill_stars_for_anonymous({{ place.average_rating|unlocalize }});
        {% endif %}
    </script>

{% endblock %}

places/templates/edit.html
{% extends 'base_with_map.html' %}
{% load static %}
{% load l10n %}

{% block content %}
    <h1>{{header}}</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.non_field_errors }}
        <div>
            {{ form.name.errors }}
            <label for="id_name">Название:</label>
            {{ form.name }}
        </div>
        <div>
            <br>
            {{ form.visibility.errors }}
            <label for="id_visibility">Кому видно:</label>
            {{ form.visibility }}
        </div>
        <div hidden>
            {{ form.latitude.errors }}
            <label for="id_latitude">Широта:</label>
            {{ form.latitude }}
        </div>
        <div hidden>
            {{ form.longitude.errors }}
            <label for="id_lonitude">Долгота:</label>
            {{ form.longitude }}
        </div>
        <div>
            {{ form.description.errors }}
            <label for="id_description">Описание:</label>
            {{ form.description }}
        </div>
        <br><button type="submit" class="save btn btn-default">Сохранить</button>
    </form>

    <div id="mapid" style="width: 600px; height: 400px;"></div>
    <script>

        {% if header == "Новое место" %}

            var mymap = L.map('mapid').setView([59.944027, 30.307717], 11);
            $("#id_latitude").val(59.944027);
            $("#id_longitude").val(30.307717);
            var marker = new L.marker([59.944027, 30.307717], {
                draggable: 'true'
             }).bindPopup("Перетащи меня в нужное место").openPopup();

        {% else %}

            var mymap = L.map('mapid').setView([{{ place.latitude|unlocalize }}, {{place.longitude|unlocalize}}], 11);
            $("#id_latitude").val({{ place.latitude|unlocalize }});
            $("#id_longitude").val({{place.longitude|unlocalize}});
            var marker = new L.marker([{{ place.latitude|unlocalize }}, {{place.longitude|unlocalize}}], {
                draggable: 'true'
             }).bindPopup("Перетащи меня в нужное место").openPopup();

        {% endif %}

        L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
            maxZoom: 18,
            attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
            id: 'mapbox.streets'
        }).addTo(mymap);

        marker.on('dragend', function(event) {
            var position = marker.getLatLng();
            marker.setLatLng(position, {
            draggable: 'true'
            }).bindPopup(position).update();
            $("#id_latitude").val(position.lat);
            $("#id_longitude").val(position.lng).keyup();
        });

        {% if header == "Новое место" %}
            <!--запрос на разрешение отслеживания геопозици-->
            navigator.geolocation.getCurrentPosition(
                function(position) {
                    marker.setLatLng([position.coords.latitude, position.coords.longitude]);
                    mymap.setView([position.coords.latitude, position.coords.longitude], 14);
                    $("#id_latitude").val(position.coords.latitude);
                    $("#id_longitude").val(position.coords.longitude);
                }
            );
         {% else %}
            marker.setLatLng([{{ place.latitude|unlocalize }}, {{place.longitude|unlocalize}}]);
            mymap.setView([{{ place.latitude|unlocalize }}, {{place.longitude|unlocalize}}], 14);
         {% endif %}

        mymap.addLayer(marker);
    </script>

{% endblock %}

places/templates/map.html
{% extends 'base_with_map.html' %}
{% load static %}
{% load l10n %}

{% block content %}

    <h1>Карта</h1>

    {% if sorted_list %}

        <div id="mapid" style="width: 800px; height: 600px;"></div>
        <script>

            var mymap = L.map('mapid').setView([55.76, 37.64], 3);


            L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
                maxZoom: 18,
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                    '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                    'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                id: 'mapbox.streets'
            }).addTo(mymap);

            {% if user.is_authenticated %}

                {% for place in secret_place_list %}
                    L.marker([{{ place.latitude|unlocalize }}, {{ place.longitude|unlocalize }}],{icon:secret_place_Icon}).addTo(mymap)
                    .bindPopup('<a href="{% url 'place_detail' pk=place.pk %}">{{ place.name }}</a>');
                {% endfor %}

                {% for place in another_place_list %}
                    L.marker([{{ place.latitude|unlocalize }}, {{ place.longitude|unlocalize }}],
                        {% if user == place.author %}
                            {icon:my_place_Icon}
                        {% else %}
                            {icon:another_place_Icon}
                        {% endif %})
                    .addTo(mymap)
                    .bindPopup('<a href="{% url 'place_detail' pk=place.pk %}">{{ place.name }}</a>');
                {% endfor %}

            {% else %}

                {% for place in sorted_list %}
                    L.marker([{{ place.latitude|unlocalize }}, {{ place.longitude|unlocalize }}],{icon:another_place_Icon}).addTo(mymap)
                    .bindPopup('<a href="{% url 'place_detail' pk=place.pk %}">{{ place.name }}</a>');
                {% endfor %}

            {% endif %}

        </script><br>

        {% if user.is_authenticated %}

            {% for place in sorted_list %}
                <div class="post">
                    <div class="date">
                        Автор места: <a href="{% url 'profile' pk=place.author.pk %}"> {{ place.author }}</a>
                    </div>
                    <h1>
                        <a href="{% url 'place_detail' pk=place.pk %}">{{ place.name }}</a>
                        {% if request.user == place.author and place.visibility == "me" %}
                            &nbsp;(секретное)
                        {% endif %}
                    </h1>
                    <p>{{ place.description|linebreaksbr|truncatewords:20  }}</p>
                    <p>
                        {% if 1 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 2 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 3 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 4 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 5 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {{ place.average_rating }}
                    </p>
                </div>
            {% endfor %}

        {% else %}

            {% for place in sorted_list %}
                <div class="post">
                    <div class="date">
                        Автор места: <a href="{% url 'profile' pk=place.author.pk %}"> {{ place.author }}</a>
                    </div>
                    <h1>
                        <a href="{% url 'place_detail' pk=place.pk %}">{{ place.name }}</a>
                    </h1>
                    <p>{{ place.description|linebreaksbr|truncatewords:20  }}</p>
                    <p>
                        {% if 1 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 2 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 3 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 4 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 5 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {{ place.average_rating }}
                    </p>
                </div>
            {% endfor %}

        {% endif %}

    {% endif %}

{% endblock %}

places/templates/places.html
{% extends 'base_with_map.html' %}
{% load l10n %}

{% block content %}

    {% if user.is_authenticated and user == profile_user %}
        <a href="{% url 'new_place' %}"><span class="glyphicon glyphicon-plus"></span></a>
    {% endif %}
    <h1>{{ header }}</h1>

    {% if place_list %}

        <div id="mapid" style="width: 800px; height: 600px;"></div>
        <script>
            var mymap = L.map('mapid').setView([55.76, 37.64], 3);

            L.tileLayer('https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4NXVycTA2emYycXBndHRqcmZ3N3gifQ.rJcFIG214AriISLbB6B5aw', {
                maxZoom: 18,
                attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
                    '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
                    'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
                id: 'mapbox.streets'
            }).addTo(mymap);

            {% for place in place_list %}
                L.marker([{{ place.latitude|unlocalize }}, {{ place.longitude|unlocalize }}]).addTo(mymap)
                .bindPopup('<a href="{% url 'place_detail' pk=place.pk %}">{{ place.name }}</a>');
            {% endfor %}

        </script>

        {% for place in place_list %}
            <div class="post">
                <h1>
                    <a href="{% url 'place_detail' pk=place.pk %}">{{ place.name }}</a>
                    {% if place.deleted %}
                        (удалено)
                    {% endif %}
                </h1>
                <p>{{ place.description|linebreaksbr|truncatewords:40  }}</p>
                <p>
                        {% if 1 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 2 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 3 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 4 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {% if 5 <= place.rounded_average_rating %}
                            <i class="fa fa-star"></i>
                        {% else %}
                            <i class="fa fa-star-o"></i>
                        {% endif %}
                        {{ place.average_rating }}
                    </p>
            </div>
        {% endfor %}
    {% else %}
        <p>Тут пока пусто.</p>
    {% endif %}

{% endblock %}